# 워크 플로우 이름 : 우분투 서버에서 빌드와 배포를 위한 워크 플로우
name: "Build and Deploy to Ubuntu Server Run"

# dev 브랜치에 push 가 발생하면 jobs가 실행되도록 이벤트 설정
on:
  push:
    branches:
      - dev # dev 브랜치에 push 가 발생하면

# 위에 설정된 push 이벤트를 실행할 job들의 순서를 정한다.
jobs:
  # 첫번째 단계 : 빌드
  build:
    runs-on: [self-hosted, reviewong-server]

    steps:
      - name: Build Next.js Project
        run: echo "Build Next.js Project" # echo:콘솔에 문자열을 출력하는 명령어

  # 두번째 단계: 테스트
  test:
    runs-on: [self-hosted, reviewong-server]

    steps:
      - name: Test Next.js Project
        run: echo "Test Next.js Project"

  # 세번째 단계: 배포
  deploy:
    runs-on: [self-hosted, reviewong-server]

    steps:
      - name: Deploy Next.js Project
        run: echo "Deploy Next.js Project"
        # listening... 문장이 뜨면 러너는 정상적으로 깃허브에 로그인 하고 action 이벤트를 수신함
        # running gob: build 가 뜨는 것을 확인 후 위 run: 코드를 /home/reviewing/www/reviewong-update.sh로 변경
